'use client';
import {useCallback,useEffect,useRef,useState, type FormEvent} from 'react';
import {CarFront,ArrowRight,MapPin,Search,Plus,ShieldCheck,Users,ArrowLeftRight,Navigation,Share2,RefreshCw,UserRound,CalendarDays,Check,Clock} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Toaster,toast} from 'sonner';
import {pakistanToday} from '@/lib/domain';
import RideMap from './ride-map';
import LocationPicker from './location-picker';
import {parsePlace,type Place} from '@/lib/locations';
type Ride={id:string;origin_point?:string|null;destination_point?:string|null;driver:string;origin:string;destination:string;stops:string;date:string;time:string;seats:number;car:string;fare:number|null;notes:string;pickup:string;dropoff:string;status:string;version:number;driverName:string;driverGender:string;occupied:number;passengers?:Person[];booking?:Booking|null;plate?:string;phone?:string;lat?:number|null;lng?:number|null;accuracy?:number;updated?:number|null;sharing?:number};
type Person={name:string;gender:string};
type Booking={id:string;status:string;message:string;reply:string};
type Detail={ride:Ride;own:boolean;booking:Booking|null;passengers:Person[];requests:(Person&Booking&{phone:string})[]};
type Me={user:{id:string;name:string}|null;profile:{name:string;gender:string;phone:string}|null};
const labels:Record<string,string>={scheduled:'Scheduled',enroute:'Driver on the way',arrived:'Driver has arrived',started:'Trip in progress',ended:'Completed',cancelled:'Cancelled',pending:'Awaiting approval',approved:'Seat approved',declined:'Request declined'};
const genders=['Not specified','Woman','Man','Non-binary'];
const weekdays=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
async function api(action:string,payload?:Record<string,unknown>){const r=await fetch(payload?'/api/carpool':'/api/carpool?'+action,payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})}:{cache:'no-store'});const data:any=await r.json();if(!r.ok)throw new Error(data.error||'Something went wrong. Please try again.');return data;}
function money(fare:number|null){return fare===null?'Negotiable':`Rs ${fare.toLocaleString('en-PK')}`;}
function dateLabel(value:string){return new Date(value+'T12:00:00+05:00').toLocaleDateString('en-PK',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Karachi'});}
function initials(name:string){return name.split(' ').slice(0,2).map(n=>n[0]).join('').toUpperCase();}
function SelectField({label,value,onChange,options}: {label:string;value:string;onChange:(s:string)=>void;options:string[]}){return <div className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger className="w-full min-h-11" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div>;}
function Field({label,name,type='text',value,defaultValue,onChange,required=true,placeholder,min,max}: {label:string;name?:string;type?:string;value?:string|number;defaultValue?:string;onChange?:(s:string)=>void;required?:boolean;placeholder?:string;min?:string|number;max?:string|number}){return <label className="field">{label}<input name={name} type={type} value={value} defaultValue={defaultValue} onChange={onChange?e=>onChange(e.target.value):undefined} required={required} placeholder={placeholder} min={min} max={max} maxLength={250}/></label>;}
function MapView({ride}: {ride?:Ride}){const has=ride?.sharing===1&&ride.lat!=null&&ride.lng!=null;return <><RideMap lat={ride?.lat} lng={ride?.lng} active={has}/><p className="muted">{has?'The pin is the latest reported position, not a predicted location.':'Explore Karachi. Search suggestions may be approximate; confirm your meeting point.'}</p></>;}
function MeetingPin({value,label}:{value?:string|null;label:string}){const p=parsePlace(value);return p?<a className="muted" style={{textDecoration:'underline'}} href={'https://www.openstreetmap.org/?mlat='+p.lat+'&mlon='+p.lng+'#map=17/'+p.lat+'/'+p.lng} target="_blank" rel="noreferrer">{label}</a>:null;}
function LocationStatus({ride}: {ride:Ride}){const [now,setNow]=useState(Date.now());useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),5000);return()=>clearInterval(t)},[]);const age=ride.updated?Math.max(0,Math.floor((now-ride.updated)/1000)):null;return <div className={'banner '+(age!==null&&age>45?'error':'')}><strong>{!ride.sharing?'Location sharing is off':age===null?'Waiting for a location':age>45?'Location updates interrupted':'Recent location available'}</strong><div>{age!==null&&ride.sharing?`Last received ${age<60?age+' seconds':Math.floor(age/60)+' minutes'} ago · Accuracy about ${Math.round(ride.accuracy||0)} m.`:'The driver must enable location sharing on their device.'}</div><div>Keep the website open. Locking the phone, switching apps or losing signal may pause updates.</div></div>;}
function RideCard({ride,onOpen,own}: {ride:Ride;onOpen:()=>void;own?:boolean}){return <article className="ridecard"><div className="ridebody"><div><div className="route"><div className="route-line"/><div className="routepoints"><div><strong>{ride.origin}</strong><small>{ride.time} PKT · {dateLabel(ride.date)}</small></div><div><strong>{ride.destination}</strong><small>{ride.stops?`Via ${ride.stops.split('|').join(' · ')}`:ride.dropoff}</small></div></div></div><div className="occupants"><Users size={16}/>{ride.occupied} confirmed · {Math.max(0,ride.seats-ride.occupied)} seats available</div></div><div className="fare"><strong>{money(ride.fare)}</strong><small>per seat · agree directly</small><div style={{marginTop:18}}><span className="badge">{labels[ride.booking?.status||ride.status]}</span></div></div></div><div className="ridefooter"><span className="avatar">{initials(ride.driverName)}</span><div className="drivertext"><strong>{ride.driverName}{own?' · You':''}</strong><small>{ride.car} · {ride.driverGender}</small></div><button className="outline" onClick={onOpen}>{own?'Manage ride':'View ride'}<ArrowRight size={16}/></button></div></article>;}
function SharedTracker({token}:{token:string}){const [ride,setRide]=useState<Ride|null>(null),[error,setError]=useState('');useEffect(()=>{let active=true;async function refresh(){try{const d=await api('track',{token});if(active){setRide(d.ride);setError('')}}catch(e){if(active){setRide(null);setError((e as Error).message)}}}refresh();const t=setInterval(refresh,10000);return()=>{active=false;clearInterval(t)}},[token]);return <main className="tracking"><a className="brand" href="/"><span className="brand-icon"><CarFront/></span>humsafar</a><div className="formcard"><p className="eyebrow">SHARED TRIP</p><h1>Follow their journey.</h1>{error?<div className="banner error" role="alert">{error}</div>:!ride?<p className="loading">Loading trip…</p>:<div className="detailstack"><h2>{ride.origin} → {ride.destination}</h2><p>{ride.driverName} · {ride.car} · {ride.plate}</p><LocationStatus ride={ride}/><MapView ride={ride}/><p className="muted">This private link expires when the trip ends, after 12 hours, or when its owner stops sharing. Anyone with the link can view these trip details. It is not an emergency service.</p></div>}</div></main>;}
export default function Carpool(){
 const [view,setView]=useState('find'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[date,setDate]=useState(pakistanToday()),[rides,setRides]=useState<Ride[]>([]),[trips,setTrips]=useState<Ride[]>([]),[me,setMe]=useState<Me>({user:null,profile:null}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<Detail|null>(null),[message,setMessage]=useState(''),[reply,setReply]=useState<Record<string,string>>({}),[gender,setGender]=useState('Not specified'),[days,setDays]=useState<number[]>([]),[shareLink,setShareLink]=useState(''),[tracking,setTracking]=useState(false),[token,setToken]=useState('');
 const [fromPoint,setFromPoint]=useState<Place|null>(null),[toPoint,setToPoint]=useState<Place|null>(null),[offerFrom,setOfferFrom]=useState(''),[offerTo,setOfferTo]=useState(''),[offerFromPoint,setOfferFromPoint]=useState<Place|null>(null),[offerToPoint,setOfferToPoint]=useState<Place|null>(null);
 const watch=useRef<number|null>(null),lastSent=useRef(0),trackingRide=useRef<string|null>(null),versions=useRef<Record<string,string>>({});
 const refreshMe=useCallback(async()=>{const d=await api('action=me');setMe(d);setGender(d.profile?.gender||'Not specified');return d as Me},[]);
 const search=useCallback(async()=>{setLoading(true);setError('');try{const params=new URLSearchParams({from,to,date});if(fromPoint)params.set('fromPoint',JSON.stringify(fromPoint));if(toPoint)params.set('toPoint',JSON.stringify(toPoint));const d=await api('action=rides&'+params);setRides(d.rides)}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[from,to,date,fromPoint,toPoint]);
 const loadTrips=useCallback(async()=>{try{const d=await api('action=trips');setTrips(d.rides);for(const r of d.rides){const sig=r.version+':'+(r.booking?.status||'');if(versions.current[r.id]&&versions.current[r.id]!==sig)toast.info(`Your ${r.origin} → ${r.destination} ride has changed. Review its status and passenger list.`);versions.current[r.id]=sig}}catch(e){setError((e as Error).message)}},[]);
 const loadDetail=useCallback(async(id:string)=>{const d=await api('action=detail&id='+encodeURIComponent(id));setDetail(d);return d as Detail},[]);
 useEffect(()=>{const params=new URLSearchParams(location.hash.slice(1));const t=params.get('trip');if(t)setToken(t);refreshMe().catch(e=>setError(e.message));search();},[]);
 useEffect(()=>{if(view==='trips'&&me.user){loadTrips();const t=setInterval(loadTrips,12000);return()=>clearInterval(t)}},[view,me.user?.id,loadTrips]);
 useEffect(()=>{if(!selected){setDetail(null);setShareLink('');return}let active=true;async function refresh(){try{const d=await api('action=detail&id='+selected);if(active)setDetail(d)}catch(e){if(active)setError((e as Error).message)}}refresh();const t=setInterval(refresh,10000);return()=>{active=false;clearInterval(t)}},[selected]);
 useEffect(()=>()=>{if(watch.current!==null)navigator.geolocation.clearWatch(watch.current)},[]);
 useEffect(()=>{if(detail&&trackingRide.current===detail.ride.id&&['ended','cancelled'].includes(detail.ride.status)){if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);watch.current=null;trackingRide.current=null;setTracking(false)}},[detail]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'search_rides',description:'Search saved carpool rides by departure, destination and date; updates the visible search results.',inputSchema:{type:'object',properties:{from:{type:'string'},to:{type:'string'},date:{type:'string',pattern:'^\\d{4}-\\d{2}-\\d{2}$'}},required:['from','to','date'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(typeof input.from!=='string'||typeof input.to!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(input.date))throw new Error('Valid route and date required');const d=await api('action=rides&'+new URLSearchParams(input));setFrom(input.from);setTo(input.to);setFromPoint(null);setToPoint(null);setDate(input.date);setRides(d.rides);setView('find');return {count:d.rides.length,rides:d.rides.map((r:Ride)=>({id:r.id,from:r.origin,to:r.destination,time:r.time,fare:r.fare}))}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
 async function mutate(action:string,data:Record<string,unknown>,success:string){setBusy(true);setError('');try{const d=await api(action,data);toast.success(success);if(selected)await loadDetail(selected);if(view==='trips')await loadTrips();return d}catch(e){setError((e as Error).message);toast.error((e as Error).message);return null}finally{setBusy(false)}}
 function needProfile(next:string){if(!me.user){setView('profile');return false}if(!me.profile){setView('profile');toast.info('Save your profile to continue.');return false}setView(next);return true}
 async function openRide(id:string){if(!me.user){setView('profile');return}setMessage('');setSelected(id);}
 async function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const d=await mutate('profile',{name:f.get('name'),phone:f.get('phone'),gender},'Profile saved');if(d){await refreshMe();setView('find')}}
 async function publishRide(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!offerFromPoint||!offerToPoint){toast.error('Choose and confirm both Karachi locations.');return}const f=new FormData(e.currentTarget),data=Object.fromEntries(f);const d=await mutate('create',{...data,originPoint:offerFromPoint,destinationPoint:offerToPoint,seats:Number(data.seats),fare:data.fare===''?null:Number(data.fare),days,stops:String(data.stops).split(',').map(s=>s.trim()).filter(Boolean).join('|')},'Your ride is listed');if(d){setDays([]);setOfferFrom('');setOfferTo('');setOfferFromPoint(null);setOfferToPoint(null);setView('trips');await loadTrips()}}
 async function share(){if(!detail)return;const d=await mutate('share',{id:detail.ride.id},'Private trip link created');if(d)setShareLink(location.origin+'/#trip='+d.token)}
 async function stopTracking(){if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);watch.current=null;const id=trackingRide.current;trackingRide.current=null;setTracking(false);if(id)await mutate('location',{id,stop:true},'Location sharing stopped')}
 async function startTracking(){if(!detail)return;if(!navigator.geolocation){toast.error('Location is unavailable in this browser.');return}if(watch.current!==null){toast.error('Stop sharing your other trip first.');return}trackingRide.current=detail.ride.id;setTracking(true);lastSent.current=0;toast.info('Allow location access when your browser asks.');watch.current=navigator.geolocation.watchPosition(async p=>{if(Date.now()-lastSent.current<8000)return;lastSent.current=Date.now();try{await api('location',{id:trackingRide.current,lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy});if(selected)await loadDetail(selected)}catch(e){toast.error((e as Error).message);if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);watch.current=null;setTracking(false)}},e=>{toast.error(e.code===1?'Location permission denied. Enable it in browser settings to share.':'Unable to get a location. Check your signal and try again.');if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);watch.current=null;setTracking(false)},{enableHighAccuracy:true,timeout:20000,maximumAge:5000})}
 if(token)return <><SharedTracker token={token}/><Toaster richColors/></>;
 const signIn=<div className="emptycard"><UserRound size={38}/><h2>Sign in to travel together</h2><p>This private test version uses ChatGPT sign-in. Customer email/password accounts are not enabled yet.</p><a className="primary" href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT</a></div>;
 return <><Toaster richColors position="top-center"/><header className="topbar"><a className="brand" href="/"><span className="brand-icon"><CarFront/></span>humsafar<span className="urdu">ہم سفر</span></a><nav><button className={view==='find'?'navactive':''} onClick={()=>setView('find')}>Find a ride</button><button className={view==='trips'?'navactive':''} onClick={()=>needProfile('trips')}>My trips</button><button className={view==='profile'?'navactive':''} onClick={()=>setView('profile')}>{me.profile?.name.split(' ')[0]||'Account'}</button></nav><button className="outline" onClick={()=>needProfile('offer')}><Plus size={18}/>Offer a ride</button></header><main className="shell"><div className="intro"><div><p className="eyebrow">GOOD COMPANY. SHARED JOURNEYS.</p><h1>{view==='find'?'Your route. Your people.':view==='offer'?'Got room for company?':view==='trips'?'Your shared journeys.':'A little about you.'}</h1><p>{view==='find'?'Find a seat with someone heading your way.':view==='offer'?'Set your route. Choose your days. Approve your passengers.':view==='trips'?'Manage requests, meet your driver, and follow your trip.':'Help your fellow travellers know who they’re riding with.'}</p></div><span className="free-label">Free to connect · Karachi pilot</span></div>{error&&<div className="banner error" role="alert">{error}<button className="subtle" onClick={()=>setError('')}>Dismiss</button></div>}{tracking&&<div className="banner"><Navigation size={17} style={{display:'inline',marginRight:8}}/>Your device is sharing location. Keep this page open.<button className="subtle" onClick={stopTracking}>Stop sharing</button></div>}
 {view==='find'&&<><form className="searchbar" onSubmit={e=>{e.preventDefault();if((from.trim()&&!fromPoint)||(to.trim()&&!toPoint)){toast.error('Choose a dropdown result or confirm a map pin for each location.');return}search()}}><LocationPicker label="Leaving from" text={from} selected={fromPoint} onText={s=>{setFrom(s);setFromPoint(null)}} onSelect={p=>{setFrom(p.label);setFromPoint(p)}}/><button className="swap" type="button" aria-label="Swap departure and destination" onClick={()=>{setFrom(to);setTo(from);setFromPoint(toPoint);setToPoint(fromPoint)}}><ArrowLeftRight size={20}/></button><LocationPicker label="Going to" text={to} selected={toPoint} onText={s=>{setTo(s);setToPoint(null)}} onSelect={p=>{setTo(p.label);setToPoint(p)}}/><label><span>Travel date</span><input aria-label="Travel date" type="date" min={pakistanToday()} required value={date} onChange={e=>setDate(e.target.value)}/></label><button disabled={loading} className="primary"><Search size={19}/>{loading?'Searching…':'Find rides'}</button></form><div className="workspace"><section><div className="sectionhead"><h2>{loading?'Looking for your ride…':`${rides.length} ${rides.length===1?'ride':'rides'} available`}</h2><span>Driver approval on every booking</span></div>{loading?<p className="loading" role="status">Loading available rides…</p>:rides.length?rides.map(r=><RideCard key={r.id} ride={r} onOpen={()=>openRide(r.id)}/>):<div className="emptycard"><CarFront size={42}/><h2>Be part of the first shared journeys.</h2><p>No rides match this date and route yet. Try another date or offer a ride.</p><button className="outline" onClick={()=>needProfile('offer')}><Plus size={17}/>Offer the first ride</button></div>}<p className="muted" style={{marginTop:16}}>Karachi pilot: choose exact places or map pins. Results match pickup and drop-off points within 1 km of your choices, not the full driving route. Leave both fields empty to browse all Karachi rides.</p></section><aside><div className="darkcard"><ShieldCheck size={30}/><h2>Know your ride.<br/>Share your journey.</h2><p>See who’s travelling before you request a seat. Follow your driver on the way to pickup.</p><div className="safetyrow"><Users size={20}/>Passenger details before booking</div><div className="safetyrow"><MapPin size={20}/>Location sharing with consent</div></div><div className="note"><h3>Your fare, your agreement.</h3><p>Discuss the fare directly with your driver. No platform payments or subscriptions.</p><ArrowRight size={20}/></div><MapView/></aside></div></>}
 {view==='profile'&&(!me.user?signIn:<form className="formcard" onSubmit={saveProfile} key={me.profile?.name||'new'}><h2>Your traveller profile</h2><div className="formgrid"><Field label="Public display name" name="name" placeholder="Your first name" defaultValue={me.profile?.name}/><SelectField label="Gender (optional, self-described)" value={gender} onChange={setGender} options={genders}/><Field label="Phone (optional)" name="phone" placeholder="+923001234567" defaultValue={me.profile?.phone} required={false}/><p className="muted">Your display name and gender appear to signed-in travellers. Your phone is shared only with your driver, or approved passengers on rides you drive.</p></div>{me.profile&&<p className="muted" style={{marginTop:16}}>Current profile: {me.profile.name} · {me.profile.gender} · {me.profile.phone||'No phone added'}</p>}<div className="actions"><button disabled={busy} className="primary">Save profile</button><a className="subtle" href="/signout-with-chatgpt?return_to=/" target="_top">Sign out</a></div></form>)}
 {view==='offer'&&<form className="formcard" onSubmit={publishRide}><h2>Offer a ride</h2><div className="formgrid"><LocationPicker label="Pickup location" text={offerFrom} selected={offerFromPoint} onText={s=>{setOfferFrom(s);setOfferFromPoint(null)}} onSelect={p=>{setOfferFrom(p.label);setOfferFromPoint(p)}}/><LocationPicker label="Drop-off location" text={offerTo} selected={offerToPoint} onText={s=>{setOfferTo(s);setOfferToPoint(null)}} onSelect={p=>{setOfferTo(p.label);setOfferToPoint(p)}}/><Field label="Pickup instructions" name="pickup" placeholder="e.g. Main entrance, Gate 2"/><Field label="Drop-off instructions" name="dropoff" placeholder="e.g. Main entrance, Gate 2"/><div className="span2"><Field label="Stops, in travel order (optional)" name="stops" placeholder="e.g. PECHS, Nursery, Shahrah-e-Faisal" required={false}/></div><Field label="First departure date" name="date" type="date" min={pakistanToday()}/><Field label="Departure time (Pakistan time)" name="time" type="time"/><div className="span2"><p className="field" style={{marginBottom:10}}>Repeat on (optional)</p><div className="dayrow">{weekdays.map((day,i)=><label className="checklabel" key={day}><Checkbox checked={days.includes(i)} onCheckedChange={v=>setDays(v?[...days,i]:days.filter(n=>n!==i))}/>{day}</label>)}</div><p className="muted" style={{marginTop:8}}>{days.length?'Creates separate departures over the next four weeks from the chosen date.':'No days selected: publish a one-time ride.'}</p></div><Field label="Passenger seats offered" name="seats" type="number" min={1} max={8}/><Field label="Proposed fare per seat (PKR, optional)" name="fare" type="number" min={0} max={100000} placeholder="Leave blank for negotiable" required={false}/><Field label="Car make, model and colour" name="car" placeholder="Toyota Corolla · White"/><Field label="Registration plate" name="plate" placeholder="Shared after passenger approval"/><label className="field span2">Ride notes (optional)<textarea name="notes" maxLength={600} placeholder="Luggage space, pickup arrangements or fare details"/></label></div><p className="muted" style={{marginTop:16}}>Each request is for one person and one seat. Only you can approve passengers. Vehicle and profile information is self-reported.</p><div className="actions"><button disabled={busy} className="primary"><Plus size={18}/>{busy?'Publishing…':'Publish ride'}</button><button type="button" className="subtle" onClick={()=>setView('find')}>Cancel</button></div></form>}
 {view==='trips'&&<><div className="tripheading"><h2>Bookings & rides you offer</h2><button className="outline" onClick={loadTrips}><RefreshCw size={16}/>Refresh</button></div><div className="banner">Passenger lists can change before departure. Updates appear here while this page is open; review the list before travelling. You can cancel your seat before the trip starts.</div>{trips.length?trips.map(r=><RideCard key={r.id} ride={r} own={r.driver===me.user?.id} onOpen={()=>openRide(r.id)}/>):<div className="emptycard"><CalendarDays size={40}/><h2>No trips just yet.</h2><p>Request a seat or publish your first ride to get started.</p><button className="outline" onClick={()=>setView('find')}>Find a ride</button></div>}</>}
 </main><footer><span>humsafar · Shared journeys across Karachi</span><span>Fares in PKR · Times in Pakistan Standard Time</span></footer>
 <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null)}}><DialogContent className="detaildialog sm:max-w-2xl"><DialogTitle>{detail?`${detail.ride.origin} → ${detail.ride.destination}`:'Loading ride…'}</DialogTitle><DialogDescription>{detail?`${dateLabel(detail.ride.date)} · ${detail.ride.time} PKT · ${labels[detail.ride.status]}`:'Fetching the latest ride details.'}</DialogDescription>{detail&&<div className="detailstack"><div className="manifest"><span className="avatar">{initials(detail.ride.driverName)}</span><div><strong>{detail.ride.driverName} · Driver</strong><p className="muted">{detail.ride.driverGender} · {detail.ride.car}{detail.ride.plate?' · '+detail.ride.plate:''}</p></div></div><div className="formgrid"><div><h3>Pickup</h3><p>{detail.ride.pickup}</p><MeetingPin value={detail.ride.origin_point} label="Open pickup pin"/></div><div><h3>Drop-off</h3><p>{detail.ride.dropoff}</p><MeetingPin value={detail.ride.destination_point} label="Open drop-off pin"/></div><div><h3>{money(detail.ride.fare)} / seat</h3><p className="muted">Final fare agreed directly</p></div><div><h3>{detail.ride.seats-detail.ride.occupied} seats available</h3><p className="muted">{detail.ride.occupied} confirmed passengers</p></div></div>{detail.ride.notes&&<p>{detail.ride.notes}</p>}{detail.ride.phone&&<p>Driver contact: <a href={'tel:'+detail.ride.phone}>{detail.ride.phone}</a></p>}<div><h3>Who’s in the car</h3><p className="muted">{detail.passengers.length?detail.passengers.map(p=>p.gender).reduce((a:string[],g:string)=>{if(!a.includes(g))a.push(g);return a},[]).map(g=>`${detail.passengers.filter(p=>p.gender===g).length} ${g==='Woman'?'women':g==='Man'?'men':g.toLowerCase()}`).join(' · '):'No approved passengers yet.'}</p>{detail.passengers.map((p,i)=><div key={i} className="manifest" style={{marginTop:8}}><span className="avatar">{initials(p.name)}</span><div><strong>{p.name}</strong><p className="muted">{p.gender}</p></div></div>)}<p className="muted" style={{marginTop:8}}>Gender is optional and self-described. Profiles and identities are not verified.</p></div>
 {!detail.own&&(!detail.booking||['cancelled','declined'].includes(detail.booking.status))&&detail.ride.status==='scheduled'&&<form onSubmit={async e=>{e.preventDefault();if(!me.profile){setSelected(null);setView('profile');toast.info('Save your profile first.');return}await mutate('request',{id:detail.ride.id,message},'Seat request sent to the driver')}}><label className="field">Message the driver<textarea required maxLength={600} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Confirm your pickup, drop-off and proposed fare."/></label><button disabled={busy} className="primary" style={{marginTop:12}}>Request one seat</button><p className="muted">Your seat is reserved only when the driver approves.</p></form>}
 {detail.booking&&<div className="banner"><strong>{labels[detail.booking.status]}</strong><p>Your message: {detail.booking.message}</p>{detail.booking.reply&&<p>Driver’s reply: {detail.booking.reply}</p>}{['pending','approved'].includes(detail.booking.status)&&['scheduled','enroute','arrived'].includes(detail.ride.status)&&<button className="subtle" disabled={busy} onClick={()=>mutate('cancelBooking',{id:detail.ride.id},'Seat request cancelled')}>Cancel my seat</button>}</div>}
 {detail.own&&<>{['scheduled','enroute','arrived'].includes(detail.ride.status)&&<form className="toolbar" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);mutate('seats',{id:detail.ride.id,seats:Number(f.get('capacity'))},'Seat capacity updated')}}><Field label="Total passenger seats" name="capacity" type="number" min={Math.max(1,detail.ride.occupied)} max={8} defaultValue={String(detail.ride.seats)}/><button className="outline" disabled={busy}>Update seats</button></form>}<h3>Passenger requests</h3>{!detail.requests.length&&<p className="muted">New requests will appear here.</p>}{detail.requests.map(r=><div key={r.id} className="formcard" style={{padding:16}}><strong>{r.name} · {r.gender}</strong><p className="status">{labels[r.status]}</p><p>{r.message}</p>{r.phone&&<p className="muted">Contact: <a href={'tel:'+r.phone}>{r.phone}</a></p>}{r.status==='pending'&&['scheduled','enroute','arrived'].includes(detail.ride.status)&&<><label className="field" style={{marginTop:10}}>Reply / fare agreement<textarea maxLength={600} value={reply[r.id]||''} onChange={e=>setReply({...reply,[r.id]:e.target.value})} placeholder="Confirm the fare and meeting point"/></label><div className="actions"><button disabled={busy||detail.ride.occupied>=detail.ride.seats} className="primary" onClick={()=>mutate('approve',{id:detail.ride.id,bookingId:r.id,reply:reply[r.id]||''},'Passenger approved')}><Check size={16}/>Approve</button><button disabled={busy} className="outline" onClick={()=>mutate('decline',{id:detail.ride.id,bookingId:r.id,reply:reply[r.id]||''},'Request declined')}>Decline</button></div></>}</div>)}<div className="actions">{({scheduled:[['enroute','On my way']],enroute:[['arrived',"I’m here"]],arrived:[['started','Start trip']],started:[['ended','End trip']]} as Record<string,string[][]>)[detail.ride.status]?.map(([status,label])=><button className="primary" disabled={busy} key={status} onClick={async()=>{if(status==='ended'&&tracking)await stopTracking();await mutate('status',{id:detail.ride.id,status},label==='End trip'?'Trip ended':label)}}>{label}</button>)}{['scheduled','enroute','arrived'].includes(detail.ride.status)&&<button className="outline" disabled={busy} onClick={()=>mutate('status',{id:detail.ride.id,status:'cancelled'},'Ride cancelled')}>Cancel ride</button>}</div></>}
 {(detail.own||detail.booking?.status==='approved')&&['enroute','arrived','started'].includes(detail.ride.status)&&<><h3>Driver location</h3><LocationStatus ride={detail.ride}/>{detail.own&&<><p className="muted">Sharing makes your location visible to approved passengers. During the trip, their private tracking links can also show it to trusted contacts.</p><button className="outline" onClick={tracking?stopTracking:startTracking}><Navigation size={18}/>{tracking?'Stop location sharing':'Allow & share my location'}</button></>}{detail.ride.sharing===1&&<MapView ride={detail.ride}/>}</>}
 {(detail.own||detail.booking?.status==='approved')&&detail.ride.status==='started'&&<div><h3>Share this trip</h3><p className="muted">Shares driver, car, route and latest driver location. Other passengers’ profiles and phone numbers stay private. In this owner-only preview, recipients cannot open links yet.</p><div className="actions"><button className="outline" disabled={busy} onClick={share}><Share2 size={18}/>Create private link</button><button className="subtle" disabled={busy} onClick={async()=>{await mutate('revokeShare',{id:detail.ride.id},'Your links are disabled');setShareLink('')}}>Stop link sharing</button></div>{shareLink&&<label className="field" style={{marginTop:12}}>Private trip link<input readOnly value={shareLink} onFocus={e=>e.target.select()}/><button className="outline" onClick={async()=>{try{await navigator.clipboard.writeText(shareLink);toast.success('Link copied')}catch{toast.info('Select the link above and copy it.')}}}>Copy link</button></label>}</div>}
 </div>}</DialogContent></Dialog></>;
}
