'use client';
import {useEffect,useId,useState} from 'react';
import {MapPin,LocateFixed,Check} from 'lucide-react';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem} from '@/components/ui/combobox';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {KARACHI,inKarachi,type Place} from '@/lib/locations';
import RideMap from './ride-map';

export default function LocationPicker({label,text,selected,onText,onSelect}:{label:string;text:string;selected:Place|null;onText:(text:string)=>void;onSelect:(place:Place)=>void}){
 const id=useId();const [items,setItems]=useState<Place[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState(false),[editing,setEditing]=useState(false),[draft,setDraft]=useState<Place|null>(null),[name,setName]=useState(''),[pinError,setPinError]=useState(''),[locating,setLocating]=useState(false),[latText,setLatText]=useState(''),[lngText,setLngText]=useState('');
 useEffect(()=>{
  const q=text.trim();const controller=new AbortController();setItems([]);setError('');
  if(q.length<3||selected||!open){setLoading(false);return()=>controller.abort()}
  setLoading(true);const timer=setTimeout(async()=>{try{const r=await fetch('/api/places?'+new URLSearchParams({q}),{signal:controller.signal});const data=await r.json() as {places?:Place[];error?:string};if(!r.ok)throw new Error(data.error||'Search unavailable');if(!controller.signal.aborted)setItems(data.places||[])}catch(e){if(!controller.signal.aborted)setError((e as Error).message)}finally{if(!controller.signal.aborted)setLoading(false)}},600);
  return()=>{controller.abort();clearTimeout(timer)};
 },[text,selected,open]);
 function edit(p:Place|null){setDraft(p);setLatText(p?String(p.lat):'');setLngText(p?String(p.lng):'');setName(p?.label||text);setPinError('');setOpen(false);setEditing(true)}
 function pick(lat:number,lng:number){if(!inKarachi(lat,lng)){setPinError('Select a point within the Karachi pilot area.');return}setLatText(String(lat));setLngText(String(lng));setPinError('');setDraft({id:`pin:${lat.toFixed(6)},${lng.toFixed(6)}`,label:name||'Map pin',address:'Karachi, Pakistan',lat,lng,source:'pin'})}
 function typeCoordinates(a:string,b:string){setLatText(a);setLngText(b);if(!a||!b||!inKarachi(Number(a),Number(b))){setPinError('Enter both coordinates within the Karachi pilot area.');return}const lat=Number(a),lng=Number(b);setPinError('');setDraft({id:`pin:${lat.toFixed(6)},${lng.toFixed(6)}`,label:name||'Map pin',address:'Karachi, Pakistan',lat,lng,source:'pin'})}
 function locate(){if(!navigator.geolocation){setPinError('Your browser does not support location access.');return}setLocating(true);navigator.geolocation.getCurrentPosition(p=>{pick(p.coords.latitude,p.coords.longitude);setLocating(false)},()=>{setPinError('Could not get your location. Check browser permission or choose a pin manually.');setLocating(false)},{enableHighAccuracy:true,timeout:15000,maximumAge:0})}
 return <div className="location-field"><label htmlFor={id}>{label}</label><Combobox items={items} filter={null} value={selected} inputValue={text} open={open} onOpenChange={setOpen} itemToStringLabel={(item:Place)=>item.label} isItemEqualToValue={(a:Place,b:Place)=>a.id===b.id} onInputValueChange={(value,details)=>{if(['input-change','input-clear','clear-press'].includes(details.reason)){onText(value);setItems([]);setOpen(true)}}} onValueChange={(value:Place|null)=>{if(value)edit(value)}}><ComboboxInput id={id} aria-label={label} placeholder="Search a Karachi place" maxLength={120} showClear={!!text} className="location-input"/><ComboboxContent className="location-results"><ComboboxList>{items.map(p=><ComboboxItem value={p} key={p.id}><MapPin size={17}/><span><strong>{p.label}</strong><small>{p.address}</small></span></ComboboxItem>)}</ComboboxList>{!items.length&&<p className="location-message" role="status">{selected?'Location selected. Use Adjust pin to change it.':loading?'Searching Karachi…':error|| (text.trim().length<3?'Type at least 3 characters to search.':'No matching places found. Choose a map pin instead.')}</p>}<p className="location-attribution">Search: Photon · © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a></p></ComboboxContent></Combobox><div className="location-tools">{selected?<span><Check size={13}/>Pin confirmed</span>:<span>Karachi only</span>}<button type="button" onClick={()=>edit(selected)}>{selected?'Adjust pin':'Choose on map'}</button></div>
 <Dialog open={editing} onOpenChange={setEditing}><DialogContent className="detaildialog sm:max-w-xl"><DialogTitle>Confirm {label.toLowerCase()}</DialogTitle><DialogDescription>Check the entrance or meeting point. Click the map to move the pin. Search suggestions may be approximate.</DialogDescription><RideMap lat={draft?.lat} lng={draft?.lng} active={!!draft} onPick={pick}/><label className="field">Place / landmark name<input maxLength={120} value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Building name, Gate 2"/></label><div className="formgrid"><label className="field">Latitude<input type="number" step="any" min={KARACHI.south} max={KARACHI.north} value={latText} onChange={e=>typeCoordinates(e.target.value,lngText)}/></label><label className="field">Longitude<input type="number" step="any" min={KARACHI.west} max={KARACHI.east} value={lngText} onChange={e=>typeCoordinates(latText,e.target.value)}/></label></div><p className="muted">Choose a public meeting point. Its name and pin will appear on the ride listing.</p>{pinError&&<p className="banner error" role="alert">{pinError}</p>}<div className="actions"><button className="outline" type="button" onClick={locate} disabled={locating}><LocateFixed size={17}/>{locating?'Locating…':'Use my location'}</button><button className="primary" type="button" disabled={!draft||!name.trim()||!!pinError} onClick={()=>{if(draft){const place={...draft,label:name.trim()};onSelect(place);setEditing(false);setOpen(false)}}}>Confirm location</button></div></DialogContent></Dialog></div>;
}
