import assert from 'node:assert/strict';
import { createTestDatabase } from './testing/database.mjs';
const {db,asUser,rpc}=await createTestDatabase();
let checks=0;
const check=(v,m)=>{assert.ok(v,m);checks++};
const denied=async(fn,code)=>{await assert.rejects(fn, e=>{assert.equal(e.code,code,e.message);return true});checks++};
const driver='00000000-0000-4000-8000-000000000001',p1='00000000-0000-4000-8000-000000000002',p2='00000000-0000-4000-8000-000000000003',unverified='00000000-0000-4000-8000-000000000004';
try {
 for(const [id,name] of [[driver,'Driver'],[p1,'Passenger One'],[p2,'Passenger Two'],[unverified,'Unverified']]){
   await db.query("insert into auth.users(id,email,email_confirmed_at) values($1,$2,$3)",[id,name.replaceAll(' ','')+'@example.test',id===unverified?null:new Date().toISOString()]);
   if(id!==unverified) await rpc(id,'profile',{name,gender:id===p1?'Woman':'Man',phone:id===driver?'+923001234567':''});
 }
 await denied(()=>rpc(null,'rides'),'42501');
 await denied(()=>rpc(unverified,'rides'),'28000');
 const tomorrow=new Date(Date.now()+86400000).toISOString().slice(0,10);
 const originPoint={id:'test:clifton',label:'Dolmen Mall Clifton',address:'Karachi',lat:24.8021172,lng:67.0302623,source:'pin'};
 const destinationPoint={id:'test:ubl',label:'UBL City Building',address:'Karachi',lat:24.8492715,lng:67.0013189,source:'pin'};
 const listing={originPoint,destinationPoint,date:tomorrow,time:'23:30',seats:1,fare:null,car:'White Corolla',plate:'TEST-123',pickup:'Public gate',dropoff:'Office entrance',days:[]};
 await rpc(driver,'create',listing);
 const ride=(await rpc(p1,'rides',{date:tomorrow})).rides[0];
 check(ride.id,'ride created');check(ride.plate===undefined&&ride.lat===undefined&&ride.phone===undefined,'private fields excluded');
 await denied(()=>rpc(driver,'create',{...listing,originPoint:{...originPoint,lat:31.5}}),'22023');
 await denied(()=>rpc(driver,'create',{...listing,destinationPoint:originPoint}),'22023');
 await denied(()=>rpc(driver,'create',{...listing,seats:1.5}),'22P02');
 await denied(()=>rpc(driver,'create',{...listing,days:[8]}),'22023');
 await denied(()=>rpc(driver,'request',{id:ride.id}),'22023');
 // Exercise the actual role grants: direct API calls cannot bypass approval.
 await denied(()=>asUser(p1,"insert into public.bookings(ride,passenger,status) values($1,$2,'approved')",[ride.id,p1]),'42501');
 await denied(()=>asUser(p1,"update public.rides set seats=8 where id=$1",[ride.id]),'42501');
 await denied(()=>asUser(p1,"select plate,lat from public.rides"),'42501');
 await denied(()=>asUser(p1,"select name from public.profiles"),'42501');
 await denied(()=>asUser(p1,"insert into public.shares(token,ride,owner,expires) values('fake',$1,$2,9999999999999)",[ride.id,p1]),'42501');
 await rpc(p1,'request',{id:ride.id,message:'Rs 300?'});
 await rpc(p2,'request',{id:ride.id,message:'Second request'});
 await denied(()=>rpc(p1,'request',{id:ride.id}),'22023');
 await denied(()=>asUser(p1,"update public.bookings set status='approved' where passenger=$1",[p1]),'42501');
 let detail=await rpc(driver,'detail',{id:ride.id});
 const first=detail.requests.find(b=>b.name==='Passenger One'),second=detail.requests.find(b=>b.name==='Passenger Two');
 await denied(()=>rpc(p1,'approve',{id:ride.id,bookingId:first.id}),'42501');
 await denied(()=>rpc(p1,'location',{id:ride.id,lat:24.85,lng:67.03,accuracy:10}),'42501');
 await denied(()=>rpc(p1,'status',{id:ride.id,status:'enroute'}),'42501');
 // Concurrent attempts still serialize through the ride lock.
 const approvals=await Promise.allSettled([rpc(driver,'approve',{id:ride.id,bookingId:first.id}),rpc(driver,'approve',{id:ride.id,bookingId:second.id})]);
 check(approvals.filter(r=>r.status==='fulfilled').length===1,'one of two approvals for last seat succeeds');
 check((await db.query("select count(*)::int n from public.bookings where status='approved'")).rows[0].n===1,'never overbooked');
 const approved=(await db.query("select passenger from public.bookings where status='approved'")).rows[0].passenger;
 const waiting=approved===p1?p2:p1;
 check((await rpc(waiting,'detail',{id:ride.id})).ride.plate===undefined,'pending cannot see plate');
 await denied(()=>rpc(driver,'status',{id:ride.id,status:'started'}),'22023');
 await rpc(driver,'status',{id:ride.id,status:'enroute'});
 await rpc(driver,'location',{id:ride.id,lat:24.85,lng:67.03,accuracy:10});
 check((await rpc(approved,'detail',{id:ride.id})).ride.lat===24.85,'approved sees pickup location');
 check((await rpc(waiting,'detail',{id:ride.id})).ride.lat===undefined,'pending cannot track');
 await rpc(driver,'status',{id:ride.id,status:'arrived'});
 await rpc(driver,'status',{id:ride.id,status:'started'});
 await denied(()=>rpc(waiting,'share',{id:ride.id}),'42501');
 await denied(()=>rpc(approved,'cancelBooking',{id:ride.id}),'22023');
 let share=await rpc(approved,'share',{id:ride.id});
 await denied(()=>rpc(null,'track',{token:share.token}),'42501');
 const tracking=(await rpc(waiting,'track',{token:share.token})).ride;
 check(tracking.lat===24.85&&!tracking.phone&&!tracking.passengers,'logged-in trusted contact sees minimum trip data');
 await rpc(approved,'revokeShare',{id:ride.id});await denied(()=>rpc(waiting,'track',{token:share.token}),'P0002');
 share=await rpc(approved,'share',{id:ride.id});await db.exec('update public.shares set expires=0');await denied(()=>rpc(waiting,'track',{token:share.token}),'P0002');
 share=await rpc(approved,'share',{id:ride.id});await rpc(driver,'status',{id:ride.id,status:'ended'});await denied(()=>rpc(waiting,'track',{token:share.token}),'P0002');
 const ended=(await db.query('select lat,lng,sharing from public.rides where id=$1',[ride.id])).rows[0];check(ended.lat===null&&ended.lng===null&&!ended.sharing,'ending removes location');
 await denied(()=>rpc(driver,'location',{id:ride.id,lat:24.85,lng:67.03,accuracy:10}),'22023');
 await rpc(driver,'create',{...listing,days:[1,3,5]});
 check((await db.query('select count(*)::int n from public.rides')).rows[0].n===13,'recurrence creates separate departures');
 const token='test-device-token-1234567890';
 await asUser(p1,'select public.humsafar_device($1,true)',[token]);
 await asUser(p2,'select public.humsafar_device($1,true)',[token]);
 let subscriptions=(await db.query('select * from public.notification_subscriptions')).rows;
 check(subscriptions.length===1&&subscriptions[0].user_id===p2,'account switch transfers device rather than duplicate');
 await asUser(p1,'select public.humsafar_device($1,false)',[token]);
 check((await db.query('select count(*)::int n from public.notification_subscriptions')).rows[0].n===1,'old user cannot unregister new owner');
 await asUser(p2,'select public.humsafar_device($1,false)',[token]);
 check((await db.query('select count(*)::int n from public.notification_subscriptions')).rows[0].n===0,'logout unregisters device');
 console.log(`${checks} PostgreSQL checks passed: grants, verified login, driver approval, capacity, private data, sharing lifecycle, recurrence and notification ownership.`);
} finally {await db.close();}
